function [p_distribute,density_distribute,X,Y,P_avg] = calLaserDistribute(E)
% E = 180;                                        % 激光脉冲能量
t = 0.7;                                        % 大气传输效率
D_spot = 70;                                    % 激光光斑直径
R_spot = D_spot/2;                              % 激光光斑半径
p_use = 0.864;                                  % 激光光斑所占的总的能量大小
P_sum = E*t*p_use;                              % 传感器接收的激光的总能量
P_ground_get = E*t;                             % 地面接收的总能量
P_avg = P_sum/(pi*(D_spot/2).^2);               % 激光的平均能量密度
mu = [0,0];                                     % 激光中心点所在位置
% sigma_dependent = D_spot/(2*1.4909);            % 计算独立的标准差
sigma_dependent = 200;
sigma = [sigma_dependent,0;0,sigma_dependent];  % 二元标准差矩阵
x = [-R_spot:1:R_spot]';                        % 数据前处理
y = [-R_spot:1:R_spot]';
[X,Y] = meshgrid(x,y);
In = [X(:),Y(:)];                               
z = P_ground_get*100*mvnpdf(In,mu,sigma);          % 独立二元高斯分布
p_distribute = reshape(z,length(x),length(y));     % 数据可视化
density_distribute = exp(-2*(X.^2+Y.^2)/D_spot^2);
end